### ISSUE TITLE
E: The value 'stretch' is invalid for APT::Default-Release as such a release is not available in the sources

### ISSUE THREAD

**Issue by dreammonkey** [JetsonHacksNano/installVSCode#1]
should I apt-get install stretch ?
I guess some apt package is still missing from my repo ?

**Comment by dreammonkey** [comment]
seems I had to:
` wget -qO - https://packagecloud.io/headmelted/codebuilds/gpgkey | sudo apt-key add -`

**Comment by JetsonHacksNano** [comment]
Interesting. The script.deb.sh script does that explicitly, I wonder why it failed on your system.

**Comment by malith1992** [comment]
Me to have the same issue. Above commands didn't solve the issue for me.

**Comment by JetsonHacksNano** [comment]
What version of L4T/JetPack are you using?

**Comment by malith1992** [comment]
> What version of L4T/JetPack are you using?

It's L4T 32.2.1 on Jetson NANO.

**Comment by JetsonHacksNano** [comment]
I would guess that it is some kind of geographical issue with access to servers. It is difficult to debug without the output of the script. The community repo key is:

# Install the community repo key
$ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0CC3FD642696BFC8

**Comment by malith1992** [comment]
> I would guess that it is some kind of geographical issue with access to servers. It is difficult to debug without the output of the script. The community repo key is:
> 
> # Install the community repo key
> $ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0CC3FD642696BFC8

I get this error when installing the community key 


uh5190@uh5190-desktop:~/installVSCode$ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0CC3FD642696BFC8
Executing: /tmp/apt-key-gpghome.8IFGKNBOnG/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0CC3FD642696BFC8
gpg: keyserver receive failed: Connection timed out


My network is going through a proxy. Is that the issue ?

**Comment by JetsonHacksNano** [comment]
The issue is that you cannot access the keyserver. I don't know if it is a proxy, firewall or geographic location issue. However, if you can't access the keyserver it won't work.
